### ISSUE TITLE
Long book titles break tabular formatting of book list

### ISSUE THREAD

**Issue by NSBum** [57uff3r/ibooks_notes_exporter#2]
Some book titles can be quite long, so that when printing the book list, the title length causes the tabular formatting to become skewed in the terminal even with fairly generous window width. Would you consider an update in which the title is truncated if the length exceeds some nominal value?

**Comment by 57uff3r** [comment]
@NSBum thank you for reporting, will take a look into this issues and will get back to you with fixes

**Comment by 57uff3r** [comment]
@NSBum your PR has been merged and the brew formula has been updated 🙏
