### ISSUE TITLE
Requesting export for specific numbers

### ISSUE THREAD

**Issue by mariomui** [57uff3r/ibooks_notes_exporter#4]
ibooks_notes_exporter export BOOK_ID > NAME.MD

Is there a argument i could use to specify --offset? 

so I can say skip the first 16 notes. I'd like to take notes incrementatally.

```sqlite
SELECT  
ZAEANNOTATION.ZANNOTATIONSELECTEDTEXT,
ZAEANNOTATION.ZANNOTATIONNOTE,
ZAEANNOTATION.ZANNOTATIONASSETID
FROM
ZAEANNOTATION
WHERE ZANNOTATIONASSETID = $1
AND ZANNOTATIONSELECTEDTEXT NOT NULL
order by ZPLLOCATIONRANGESTART ASC, ZANNOTATIONCREATIONDATE ASC
LIMIT -1 OFFSET $2
```

Specifically something like this. Unfortunately it'll take me some time to contribute to your repository to make these changes as I haven't touched go before. The above is a working query. 
Currently i am writing down the number of notes say, 16 from chapter 1, then taking a look at the full number of notes, (32) then using the subtraction as an offset.
updated_notes_count - previous_notes_count = offset

**Comment by 57uff3r** [comment]
@mariomui 👋 please check out a new updated version
